version: '3'

services:
  exchange-rates-app-container:
    image: top-news-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8082:8080"
